# Fresh deployment with Backend.AI Manager enabled
manager:
  enabled: true
  replicaCount: 1
  image:
    registry: docker.io
    repository: nginx  # Placeholder image for testing
    tag: "1.25"
  
  service:
    type: ClusterIP
    port: 8080
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Disable other Backend.AI services for focused testing
agent:
  enabled: false

storageProxy:
  enabled: false

appProxy:
  enabled: false

webServer:
  enabled: false

# Simplified PostgreSQL configuration for Manager
postgresql:
  enabled: true
  auth:
    postgresPassword: "securepass123"
    password: "securepass123"
    username: "postgres"
    database: "backend_ai"
  primary:
    persistence:
      enabled: true
      size: 8Gi

redis:
  enabled: true
  auth:
    enabled: false
    password: ""
  master:
    persistence:
      enabled: true
      size: 8Gi

etcd:
  enabled: true
  auth:
    rbac:
      create: false
  persistence:
    enabled: true
    size: 8Gi