# Backend.AI deployment with Manager enabled
manager:
  enabled: true
  replicaCount: 1
  image:
    registry: docker.io
    repository: nginx  # Using nginx as placeholder since Backend.AI images require authentication
    tag: "1.25"
  
  service:
    type: ClusterIP
    port: 8080
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Keep other services disabled for focused testing
agent:
  enabled: false

storageProxy:
  enabled: false

appProxy:
  enabled: false

webServer:
  enabled: false

# Infrastructure services (already working)
postgresql:
  enabled: true
  auth:
    postgresPassword: "test123"
    username: "postgres" 
    password: "test123"
    database: "backend_ai"
  primary:
    persistence:
      enabled: true
      size: 2Gi
    initdb:
      scripts: {}

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 1Gi
  replica:
    persistence:
      enabled: true
      size: 1Gi

etcd:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
  replicaCount: 1