# Updated Backend.AI deployment with cr.backend.ai images
# Using nginx as placeholder since cr.backend.ai requires authentication

# Backend.AI Manager
manager:
  enabled: true
  replicaCount: 1
  image:
    registry: docker.io
    repository: nginx  # Placeholder: should be cr.backend.ai/stable/backend.ai-manager:24.03
    tag: "1.25"
  
  service:
    type: ClusterIP
    port: 8080
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Backend.AI Agent  
agent:
  enabled: true
  replicaCount: 1
  image:
    registry: docker.io
    repository: nginx  # Placeholder: should be cr.backend.ai/stable/backend.ai-agent:24.03
    tag: "1.25"
  
  service:
    type: ClusterIP
    port: 6011
  
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
      # nvidia.com/gpu: 1  # Commented out for testing
    requests:
      cpu: 500m
      memory: 1Gi
  
  gpu:
    enabled: false  # Disabled for testing

# Backend.AI Storage Proxy
storageProxy:
  enabled: true
  replicaCount: 1
  image:
    registry: docker.io
    repository: nginx  # Placeholder: should be cr.backend.ai/stable/backend.ai-storage-proxy:24.03
    tag: "1.25"
  
  service:
    type: ClusterIP
    port: 6021
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Backend.AI App Proxy
appProxy:
  enabled: true
  
  coordinator:
    enabled: true
    replicaCount: 1
    image:
      registry: docker.io
      repository: nginx  # Placeholder: should be cr.backend.ai/stable/backend.ai-app-proxy-coordinator:24.03
      tag: "1.25"
    service:
      type: ClusterIP
      port: 10200
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
  
  worker:
    enabled: true
    replicaCount: 2
    image:
      registry: docker.io
      repository: nginx  # Placeholder: should be cr.backend.ai/stable/backend.ai-app-proxy-worker:24.03
      tag: "1.25"
    service:
      type: ClusterIP
      port: 10201
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi

# Backend.AI Web Server
webServer:
  enabled: true
  replicaCount: 1
  image:
    registry: docker.io
    repository: nginx  # Placeholder: should be cr.backend.ai/stable/backend.ai-web-server:24.03
    tag: "1.25"
  
  service:
    type: ClusterIP
    port: 8090
  
  ingress:
    enabled: true
    className: ""
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: backend.ai.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

# Infrastructure services with optimized resources
postgresql:
  enabled: true
  auth:
    postgresPassword: "securepass123"
    password: "securepass123"
    username: "postgres"
    database: "backend_ai"
  global:
    postgresql:
      auth:
        postgresPassword: "securepass123"
  primary:
    persistence:
      enabled: true
      size: 8Gi

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 4Gi
  replica:
    persistence:
      enabled: true
      size: 4Gi

etcd:
  enabled: true
  auth:
    rbac:
      create: false
  persistence:
    enabled: true
    size: 4Gi
  replicaCount: 1