{{- if .Values.coordinator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-ai-app-proxy.fullname" . }}-coordinator
  labels:
    {{- include "backend-ai-app-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
  {{- with .Values.coordinator.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.coordinator.service.type }}
  ports:
    - port: {{ .Values.coordinator.service.port }}
      targetPort: {{ .Values.coordinator.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "backend-ai-app-proxy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
{{- end }}