{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-ai-app-proxy.fullname" . }}-worker
  labels:
    {{- include "backend-ai-app-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with .Values.worker.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: {{ .Values.worker.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "backend-ai-app-proxy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}