{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "backend-ai-manager.fullname" . }}
  labels:
    {{- include "backend-ai-manager.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "backend-ai-manager.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- else }}
  egress:
    - to: []
  {{- end }}
{{- end }}