apiVersion: v1
kind: Secret
metadata:
  name: backend-ai-appproxy-secret
  namespace: backend-ai
type: Opaque
stringData:
  # 반드시 변경해서 사용할 것
  jwt-secret: "CHANGE_ME_jwt_secret_min32chars"
  api-secret: "CHANGE_ME_api_secret_min32chars"
  permit-hash-secret: "CHANGE_ME_permit_hash_secret"
  postgres-password: "CHANGE_ME_postgres_password"
