apiVersion: v2
name: backend-ai-agent
description: A Helm chart for Backend.AI Agent deployment
type: application
version: 0.1.0
appVersion: "23.09"

keywords:
  - backend.ai
  - agent
  - computing
  - gpu
  - containers

home: https://backend.ai
sources:
  - https://github.com/lablup/backend.ai

maintainers:
  - name: Backend.AI Team
    email: contact@lablup.com

dependencies:
  - name: redis
    version: "21.2.13"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: etcd
    version: "12.0.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: etcd.enabled

annotations:
  category: Agent